In [1]:
import pandas as pd
import numpy as np

In [4]:
trt = pd.read_csv('../datasets/aragon/aragon_transhist.csv')

trt

,Unnamed: 0,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Quantity,Method
0,0,0x05d30ce7de548929fcce0d07d0d92f8b8e4837949cd7...,11115153,1603490923,2020-10-23 22:08:43,0x0000000000000000000000000000000000000000,0x078bebc744b819657e1927bf41ab8c74cbbf912d,"39,609,523.80952380954",Execute Transaction
1,1,0x6ba4506db1b48f9b265cb92dd8e5a80046c6978b4238...,11117540,1603522048,2020-10-24 06:47:28,0x078bebc744b819657e1927bf41ab8c74cbbf912d,0x4cb3fd420555a09ba98845f0b816e45cfb230983,0.1606202,Migrate
2,2,0x42d16043f9280ba168c0542ca3464511ca9ec2e99a50...,11117553,1603522239,2020-10-24 06:50:39,0x4cb3fd420555a09ba98845f0b816e45cfb230983,0xb9d8025a929ad4d3758a1b8536b4dd1a1293ef75,0.1606202,Transfer
3,3,0x5b7155978d8b0460f302da55785581be9c1e3a2cb148...,11118081,1603529222,2020-10-24 08:47:02,0x078bebc744b819657e1927bf41ab8c74cbbf912d,0x57c2570f1a4228a3aeff4fe533826c2a04a2d52f,87.457810404166284639,Approve And Call
4,4,0x52ebc91ca23ed6fc763c7d5f23d47e41b14884b19d3e...,11118132,1603529914,2020-10-24 08:58:34,0x57c2570f1a4228a3aeff4fe533826c2a04a2d52f,0xd202dd30921a95eef92d83b265af691b74a2b946,4,Transfer
...,...,...,...,...,...,...,...,...,...
120246,3195,0x292aad2cb563cc6cbaf468418d3b2881f406bea8f2ae...,14545753,1649429052,2022-04-08 14:44:12,0xa1006d0051a35b0000f961a8000000009ea8d2db,0x73eba399fbbea50852359ff8b8d0e3eba1f22500,444.253259269305149757,-
120247,3196,0x84d53580dfc450221d263fd4a78df2f8d0602fc024a4...,14545939,1649431460,2022-04-08 15:24:20,0xe93381fb4c4f14bda253907b18fad305d799241a,0x025ac4b20da30a7f00589298536e303210d680c3,885.48037588,Transfer
120248,3197,0xa0867d560ca1d3afa56f6c32af38c7fa74816da08d89...,14545949,1649431643,2022-04-08 15:27:23,0x9def9511fec79f83afcbffe4776b1d817dc775ae,0x98c3d3183c4b8a650614ad179a1a98be0a8d6b8e,"1,523.565967763637784906",-
120249,3198,0x1485dcf5d29d6f67c7b73ee5f610fc35a736797b1b35...,14545954,1649431718,2022-04-08 15:28:38,0x025ac4b20da30a7f00589298536e303210d680c3,0xb5f54ac4466f5ce7e0d8a5cb9fe7b8c0f35b7ba8,885.48037588,Lock
120250,3199,0x77bd4d98c1af84aa5dbb099f09c169dd033e98132e03...,14546214,1649435313,2022-04-08 16:28:33,0x9def9511fec79f83afcbffe4776b1d817dc775ae,0x98c3d3183c4b8a650614ad179a1a98be0a8d6b8e,"1,418.165501770086563583",-

In [5]:
trt.Method.value_counts()

Transfer                        58817
-                               35747
Approve And Call                 5882
Swap                             3648
Swap Exact Tokens For Tokens     2266
                                ...
Propose Price                       1
Close Sandwich_Ybt GMB              1
Open Sandwich_sl Ykeo               1
Add L1Transaction                   1
Execute Transaction                 1
Name: Method, Length: 127, dtype: int64

In [6]:
trt.Txhash.value_counts()

0x74204375ea4d0afeaeeb5811b7822ea3aa1efb39a51afc71ba6f7e3524f86f67    49
0x0b4548752c4c08ea8a641ccc83b3ec4b7da74c842a91cdd73d91ff0d18d19d06    42
0x8edda56d49e3a33af2d006ccf492e2b754ad973083b65ae6c626df9a85001371    33
0xa996f752447b98e667f35a28863f2b721a81c75db33d25b24f2ee890cce85590    33
0xf500c6e2a54e1ab8859a9b7a6639126e8b2413267584b59483a1beca61afa573    31
                                                                      ..
0x552e24b5757fa41d2a8805e2de41c4e365037c9ef10caf08e3cb2f90789b2ee4     1
0xd78a02118aa1f4cc128c6555f4b2f467d86a6eb1241b4383312f56e68e9f4d59     1
0x31567e0bc467f5d39b452a23d7306d1df5eb78b323aae619655a9f05f2f4c529     1
0x93774ed97a210a27a5e67a9412aa50ba9227dab082deeb98d1c91b564896989f     1
0x77bd4d98c1af84aa5dbb099f09c169dd033e98132e0396c697d4d0dae32f8e12     1
Name: Txhash, Length: 106556, dtype: int64

In [7]:
trt.loc[trt['Method'] == 'Exec Transaction']

,Unnamed: 0,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Quantity,Method
654,654,0xb1691bbc5f0c7d8b315fafae87d75f9deac81b521471...,11153397,1603997082,2020-10-29 18:44:42,0xd87b52a2545064aa2fd7dc8ab7831e1e8d7f0bf6,0xde4a25a0b9589689945d842c5ba0cf4f0d4eb3ac,"4,040.404040404040341987",Exec Transaction
655,655,0xb1691bbc5f0c7d8b315fafae87d75f9deac81b521471...,11153397,1603997082,2020-10-29 18:44:42,0xde4a25a0b9589689945d842c5ba0cf4f0d4eb3ac,0xde0999ee4e4bea6fecb03bf4ebef2626942ec6f5,"3,999.999999999999938566",Exec Transaction
656,656,0xb1691bbc5f0c7d8b315fafae87d75f9deac81b521471...,11153397,1603997082,2020-10-29 18:44:42,0xde4a25a0b9589689945d842c5ba0cf4f0d4eb3ac,0xd87b52a2545064aa2fd7dc8ab7831e1e8d7f0bf6,40.404040404040403421,Exec Transaction
2230,2230,0x9d1871873ffedf5ebebaafb47378f47f3d253fdbe5e9...,11205832,1604693305,2020-11-06 20:08:25,0x078bebc744b819657e1927bf41ab8c74cbbf912d,0x3fd8462e467708e5d1dd4ad6becf4058d4ccbd8d,"17,855.582961275444336315",Exec Transaction
2235,2235,0x3339a83adebb8a374408a574a76aabfc595ae6ba2041...,11205913,1604694268,2020-11-06 20:24:28,0x078bebc744b819657e1927bf41ab8c74cbbf912d,0x27f0e8beccfa594f4b08c24226ce75c535b900ea,"91,855.6860127699917915",Exec Transaction
...,...,...,...,...,...,...,...,...,...
119321,2270,0x8edda56d49e3a33af2d006ccf492e2b754ad973083b6...,14495432,1648749291,2022-03-31 17:54:51,0xd152f549545093347a162dce210e7293f1452150,0xac2283f551ca68fa83fbab64453246d57f9e0f4f,9.72256633196117,Exec Transaction
119393,2342,0x7733c776c2ce9f37f8ab606c50ea06078053f596482f...,14501365,1648829484,2022-04-01 16:11:24,0xc88b73fb980d3d360455e6ef50d7c63b1111ed5f,0xcd18eaa163733da39c232722cbc4e8940b1d8888,"11,249.99999999998457436",Exec Transaction
119395,2344,0x928e5d3f3be46f5cad8d753c377993bf536399e2c1f2...,14501396,1648829814,2022-04-01 16:16:54,0xc88b73fb980d3d360455e6ef50d7c63b1111ed5f,0xcd18eaa163733da39c232722cbc4e8940b1d8888,"44,999.99999999996545746",Exec Transaction
119399,2348,0x1745a28592de973e24ef73ac39def2bd3ed3ec8cf035...,14501483,1648830810,2022-04-01 16:33:30,0xc88b73fb980d3d360455e6ef50d7c63b1111ed5f,0xbc02417b8fdf8c581be1ed02b4664b61964cbdb8,"5,000",Exec Transaction
119402,2351,0x0da42c6f6f69f44fae2f965879ae734841ceb2b54d05...,14501515,1648831188,2022-04-01 16:39:48,0xc88b73fb980d3d360455e6ef50d7c63b1111ed5f,0xcd18eaa163733da39c232722cbc4e8940b1d8888,"14,999.999999999908839786",Exec Transaction